name: flow
favicon: null
layout_spectrum: 0.1325201508589089
typography_spectrum: 0.42504227068275213
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.675355538725853
  lightness: 0.862226611468941
  saturation: 0.40891141816973686
  rhythmicContrast: 0.16200961056165397
purpose: []
